bases:
- ../../base
patches:
- memorylimit_patch.yaml
- cpulimit_patch.yaml
- liveness_patch.yaml
- readiness_patch.yaml
- applicationconfig_patch.yaml
configMapGenerator:
- name: hello-cm
  files:
  - application.conf
