apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30000
    port: 8080
    targetPort: 8080
  - name: prometheus
    port: 5556
    targetPort: 5556
  selector:
    app: hello
