apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher
        image: serrodcal/istio-publisher:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
