apiVersion: v1
kind: Service
metadata:
  name: publisher
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: prometheus
    port: 5556
    targetPort: 5556
  selector:
    app: publisher
