apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  template:
    spec:
      containers:
      - name: publisher
        resources:
          requests:
            cpu: "25m"
          limits:
            cpu: "2"
