apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  template:
    spec:
      containers:
      - name: publisher
        resources:
          requests:
            memory: "786Mi"
          limits:
            memory: "1024Mi"
