apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  template:
    spec:
      containers:
      - name: publisher
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
