apiVersion: apps/v1
kind: Deployment
metadata:
  name: formatter
spec:
  template:
    spec:
      containers:
      - name: formatter
        resources:
          requests:
            cpu: "25m"
          limits:
            cpu: "2"
