apiVersion: apps/v1
kind: Deployment
metadata:
  name: formatter
spec:
  template:
    spec:
      containers:
      - name: formatter
        resources:
          requests:
            memory: "786Mi"
          limits:
            memory: "1024Mi"
