apiVersion: apps/v1
kind: Deployment
metadata:
  name: formatter
spec:
  template:
    spec:
      containers:
      - name: formatter
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
